[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/Toolboss.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/Toolboss.html"
  status = 200
  force = true
